### ISSUE TITLE
 Request For Protocol 21 Support

### ISSUE THREAD

**Issue by centurvfx** [Caball009/Call-of-Duty-4-X-Demo-Tool#1]
COD4X received a new update, and the tool doesn't work anymore with demos recorded in the current version of the game. I would like to ask if support for the new protocol will ever be implemented.

**Comment by Caball009** [comment]
It'll most likely be updated in a couple of weeks. 

If you can't wait that long, you can modify the demo files in the meantime. Open your demo with any hex editor. If it's a CoD4X demo, you'll notice that the first byte is [02] or [0x02]. Demos from the latest protocol will have [15] or [0x15] (v21) as second byte. If you change this to [14] or [0x14] (v20) and save it, you should be able to use the new demo file with the demo tool.

**Comment by Caball009** [comment]
Adding support for CoD4X v21 has taken much longer than anticipated, but is still on the to-do list.

**Comment by Caball009** [comment]
Issue solved in v0.99.1 by adding support for CoD4X v21 demos.
