### ISSUE TITLE
Make an output folder

### ISSUE THREAD

**Issue by eirisocherry** [Caball009/Call-of-Duty-4-X-Demo-Tool#3]
Could you, please, make a separate output folder for converted demos?
![Screenshot_3](https://github.com/Caball009/Call-of-Duty-4-X-Demo-Tool/assets/115040224/5935368c-d6ad-466a-a8fe-0f6b2f7ab1ef)

Because selecting converted demos 1 by 1 is a bit tedious
![Screenshot_4](https://github.com/Caball009/Call-of-Duty-4-X-Demo-Tool/assets/115040224/69f903dc-b295-4e94-8586-d75795f9dca9)

**Comment by Caball009** [comment]
It's a not bad idea, but other projects are taking up my time currently, so I don't think this will be implemented any time soon.

FYI, you don't need to have the demos in the same directory as the executable. You also don't need to select files one by one, if you sort files by creation time or search a given directory for ".1.dm_1" (unless you're cutting demos).

**Comment by eirisocherry** [comment]
"if you sort files by creation time" 
damn, forgot about this, thank you
